config/routes.rb
Rails.application.routes.draw do
  
  root 'todolists#index'
  # get 'persons/profile', as: 'user_root'
  devise_for :users
  
  
  resources :todolists do
     resources :tasks
     put '/tasks/:id/upsort', to: 'tasks#upsort', as: 'upsort'
     put '/tasks/:id/downsort', to: 'tasks#downsort', as: 'downsort'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todolist
  acts_as_list scope: :todolist
  validates :name, presence: true,
  length: { minimum: 1 }
end

app/models/todolist.rb
class Todolist < ApplicationRecord
    belongs_to :user
    has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
    validates :title, presence: true,
    length: { minimum: 1 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :todolists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 
      def index
        @tasks=Task.all
      end
   
      def edit
        @task = Task.find(params[:id])
      end

      def show
        @task = Task.where(id: params[:id])
      end

      def update
        @task = Task.find(params[:id])   
        if @task.update(task_params)
          redirect_to todolists_path      
        else
          render 'edit'
        end
      end

      def create
        @todolist = Todolist.find(params[:todolist_id])
        @task = @todolist.tasks.create(task_params)
        redirect_to todolists_path
      end

      def destroy
        @todolist = Todolist.find(params[:todolist_id])
        @task = @todolist.tasks.find(params[:id])
        @task.destroy
        redirect_to todolists_path
      end

      def upsort
        task = Task.find_by(id: params[:id])
        task.move_higher
        redirect_to root_path
      end

      def downsort
        task = Task.find_by(id: params[:id])
        task.move_lower
        redirect_to root_path
      end

     private
        def task_params
          params.require(:task).permit(:name, :status, :date_end)
        end   
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :authenticate_user!

    def index
      @todolists = Todolist.where(user: current_user)             
    end

    def show
      @todolist = Todolist.where(user: current_user).find(params[:id]) 
    end

    def new
      @todolist = Todolist.new
    end

    def edit
      @todolist = Todolist.find(params[:id])
    end

    def create
        @todolist = Todolist.new(title: "Project",user_id: current_user.id)
        if @todolist.save
         redirect_to todolists_path
        else
            render 'new'
        end
    end

    def update
        @todolist = Todolist.find(params[:id])      
        if @todolist.update(todolist_params)
          redirect_to todolists_path      
        else
          render 'edit'
        end
      end
    
    def destroy
       @todolist = Todolist.find(params[:id])
       @todolist.destroy
       redirect_to todolists_path
     end

    


    private
        def todolist_params
           params.require(:todolist).permit(:title, :text, :user_id)
        end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo_List_RubyGarage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
 
  </head>

  <body>
  
  
    <div class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
     <div><a class="navbar-brand" href="#">ToDoList</a></div>
     <div>
        
       <div class="navbar-nav">
        <% if user_signed_in? %>
            <span class="nav-item nav-link">Здравствуйте, <%= current_user.email %></span>
            <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-item nav-link text-dark" %>
        <% else %>
            <%= link_to "Вход", new_user_session_path, class: "nav-item nav-link" %>
            <%= link_to "Регистрация", new_user_registration_path, class: "nav-item nav-link" %>
        <% end %>
       </div>
     </div>
    </div>

    <%= yield %>
  
  </body>
</html>

app/views/tasks/edit.html.haml
<center>
<h1>Editing task</h1>
= simple_form_for @task, url: todolist_task_path, method: :put do |f|
  %p

    = f.input_field  :name
  %p
    = f.input :status
  %p
    = f.submit
    
  %p
    = link_to 'Back', todolists_path
</center>

app/views/tasks/show.html.haml
%p
  %strong Title:
  = @task.name
%p

app/views/todolists/_form.html.haml
= form_with(model: @todolist, local: true) do |form|
  %p
   
    = form.text_field :title 
 
  %p
    = form.submit 

app/views/todolists/edit.html.haml
<center>
<h1>Editing todolist</h1>

= render 'form'

= link_to 'Back', todolists_path
</center>

app/views/todolists/index.html.haml
<center>
%br
%br
%h2
  SIMPLE TODO LISTS
  %br
%h4
  %small.text-muted FROM RUBY GARAGE
%br
.container
  - @todolists.each do |todolist| 
    .row.card-header.align-items-center.pr-0
      .pr-3.text-left.calendar_icon
        %i.fas.fa-calendar-alt
      .col-9.text-left.p-0
        = todolist.title
      .col-2.text-right.ed_del_icon      
        = link_to '', edit_todolist_path(todolist), class: 'ed_del_icon fas fa-pencil-alt'
        = "|"
        = link_to '', todolist_path(todolist), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'ed_del_icon fas fa-trash-alt'
          
    
    .div
      = simple_form_for Task.new, url: todolist_tasks_path(todolist.id) do |f|
        .row.p-1.add_task.align-items-center      
          .col.p-0.plus_icon
            %i.fas.fa-plus
          
          .col-9.p-0  
            = f.input_field :name, class:'form-control', placeholder: "Start typing here to create a task..."           
          .col-2.pl-0 
            = f.submit "Add Task", class: 'btn btn-primary color_button'
        .row.align-items-center.bg-white
          .col.text-center
            = f.input_field :date_end, as: :datetime   
        
    .row.text-center.bg-white.card-body.align-items-center.p-0
      -todolist.tasks.each do |task|
        - if task.status then
          .col-1.border.pb_pt
            = check_box_tag 'task_status[]', task.status, true
          .col-7.border.pb_pt.text-left
            %strike= task.name
          .col-2.border.pb_pt.text-center.p_date
            = task.date_end.to_formatted_s(:short)
        - else
          .col-1.border.pb_pt
            = check_box_tag 'task_status[]', task.status
          .col-7.border.pb_pt.text-left
            = task.name
          .col-2.border.pb_pt.text-center.p_date
            = task.date_end.to_formatted_s(:short)
           
          
        .col-2.border.pb_pt.text-right
          = link_to '', todolist_upsort_path(todolist_id: todolist.id, id: task.id), method: :put, class: 'fas fa-sort-up'
          = link_to '', todolist_downsort_path(todolist_id: todolist.id, id: task.id), method: :put, class: 'pos fas fa-sort-down'
          = "|" 
          = link_to '', edit_todolist_task_path(todolist_id: todolist.id, id: task.id), class: 'fas fa-pencil-alt'
          = "|"
          = link_to '', [task.todolist, task], method: :delete, data: { confirm: 'Вы уверены?' }, class: 'fas fa-trash-alt'
    %p

  = simple_form_for Todolist.new do |f|   
    = f.button :submit, "+ Add TODO List", class: 'btn btn-primary add_project'

  %br
  %p.text-white
    ="@Ruby   Garage"





     
        

app/views/todolists/new.html.haml
<center>
<h1>New ToDoList</h1>

= render 'form'

= link_to 'Back', todolists_path
</center>

app/views/todolists/show.html.haml
%p
  %strong Title:
  = @todolist.title
%p
  %strong Text:
  = @todolist.text